// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CDeepCopy
SEXP CDeepCopy(SEXP inAddr, SEXP outAddr, SEXP rowInds, SEXP colInds, SEXP typecast_warning);
RcppExport SEXP bigmemory_CDeepCopy(SEXP inAddrSEXP, SEXP outAddrSEXP, SEXP rowIndsSEXP, SEXP colIndsSEXP, SEXP typecast_warningSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type inAddr(inAddrSEXP );
        Rcpp::traits::input_parameter< SEXP >::type outAddr(outAddrSEXP );
        Rcpp::traits::input_parameter< SEXP >::type rowInds(rowIndsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type colInds(colIndsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type typecast_warning(typecast_warningSEXP );
        SEXP __result = CDeepCopy(inAddr, outAddr, rowInds, colInds, typecast_warning);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
