// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GetIndivMatrixElements
SEXP GetIndivMatrixElements(SEXP bigMatAddr, SEXP col, SEXP row);
RcppExport SEXP _bigmemory_GetIndivMatrixElements(SEXP bigMatAddrSEXP, SEXP colSEXP, SEXP rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    rcpp_result_gen = Rcpp::wrap(GetIndivMatrixElements(bigMatAddr, col, row));
    return rcpp_result_gen;
END_RCPP
}
// GetIndivVectorMatrixElements
SEXP GetIndivVectorMatrixElements(SEXP bigMatAddr, NumericVector elems);
RcppExport SEXP _bigmemory_GetIndivVectorMatrixElements(SEXP bigMatAddrSEXP, SEXP elemsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type elems(elemsSEXP);
    rcpp_result_gen = Rcpp::wrap(GetIndivVectorMatrixElements(bigMatAddr, elems));
    return rcpp_result_gen;
END_RCPP
}
// ReorderRIntMatrix
void ReorderRIntMatrix(SEXP matrixVector, SEXP nrow, SEXP ncol, SEXP orderVec);
RcppExport SEXP _bigmemory_ReorderRIntMatrix(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP orderVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type orderVec(orderVecSEXP);
    ReorderRIntMatrix(matrixVector, nrow, ncol, orderVec);
    return R_NilValue;
END_RCPP
}
// ReorderRNumericMatrix
void ReorderRNumericMatrix(SEXP matrixVector, SEXP nrow, SEXP ncol, SEXP orderVec);
RcppExport SEXP _bigmemory_ReorderRNumericMatrix(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP orderVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type orderVec(orderVecSEXP);
    ReorderRNumericMatrix(matrixVector, nrow, ncol, orderVec);
    return R_NilValue;
END_RCPP
}
// ReorderBigMatrix
void ReorderBigMatrix(SEXP address, SEXP orderVec);
RcppExport SEXP _bigmemory_ReorderBigMatrix(SEXP addressSEXP, SEXP orderVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type orderVec(orderVecSEXP);
    ReorderBigMatrix(address, orderVec);
    return R_NilValue;
END_RCPP
}
// ReorderRIntMatrixCols
void ReorderRIntMatrixCols(Rcpp::IntegerMatrix matrixVector, SEXP nrow, SEXP ncol, Rcpp::IntegerVector orderVec);
RcppExport SEXP _bigmemory_ReorderRIntMatrixCols(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP orderVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type orderVec(orderVecSEXP);
    ReorderRIntMatrixCols(matrixVector, nrow, ncol, orderVec);
    return R_NilValue;
END_RCPP
}
// ReorderRNumericMatrixCols
void ReorderRNumericMatrixCols(Rcpp::NumericMatrix matrixVector, SEXP nrow, SEXP ncol, Rcpp::IntegerVector orderVec);
RcppExport SEXP _bigmemory_ReorderRNumericMatrixCols(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP orderVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type orderVec(orderVecSEXP);
    ReorderRNumericMatrixCols(matrixVector, nrow, ncol, orderVec);
    return R_NilValue;
END_RCPP
}
// ReorderRRawMatrixCols
void ReorderRRawMatrixCols(Rcpp::RawMatrix matrixVector, SEXP nrow, SEXP ncol, Rcpp::IntegerVector orderVec);
RcppExport SEXP _bigmemory_ReorderRRawMatrixCols(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP orderVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawMatrix >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type orderVec(orderVecSEXP);
    ReorderRRawMatrixCols(matrixVector, nrow, ncol, orderVec);
    return R_NilValue;
END_RCPP
}
// ReorderBigMatrixCols
void ReorderBigMatrixCols(SEXP address, SEXP orderVec);
RcppExport SEXP _bigmemory_ReorderBigMatrixCols(SEXP addressSEXP, SEXP orderVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type orderVec(orderVecSEXP);
    ReorderBigMatrixCols(address, orderVec);
    return R_NilValue;
END_RCPP
}
// OrderRIntMatrix
SEXP OrderRIntMatrix(SEXP matrixVector, SEXP nrow, SEXP columns, SEXP naLast, SEXP decreasing);
RcppExport SEXP _bigmemory_OrderRIntMatrix(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP columnsSEXP, SEXP naLastSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type columns(columnsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type naLast(naLastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(OrderRIntMatrix(matrixVector, nrow, columns, naLast, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// OrderRNumericMatrix
SEXP OrderRNumericMatrix(SEXP matrixVector, SEXP nrow, SEXP columns, SEXP naLast, SEXP decreasing);
RcppExport SEXP _bigmemory_OrderRNumericMatrix(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP columnsSEXP, SEXP naLastSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type columns(columnsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type naLast(naLastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(OrderRNumericMatrix(matrixVector, nrow, columns, naLast, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// OrderBigMatrix
SEXP OrderBigMatrix(SEXP address, SEXP columns, SEXP naLast, SEXP decreasing);
RcppExport SEXP _bigmemory_OrderBigMatrix(SEXP addressSEXP, SEXP columnsSEXP, SEXP naLastSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type columns(columnsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type naLast(naLastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(OrderBigMatrix(address, columns, naLast, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// OrderRIntMatrixCols
SEXP OrderRIntMatrixCols(SEXP matrixVector, SEXP nrow, SEXP ncol, SEXP rows, SEXP naLast, SEXP decreasing);
RcppExport SEXP _bigmemory_OrderRIntMatrixCols(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP rowsSEXP, SEXP naLastSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type naLast(naLastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(OrderRIntMatrixCols(matrixVector, nrow, ncol, rows, naLast, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// OrderRNumericMatrixCols
SEXP OrderRNumericMatrixCols(SEXP matrixVector, SEXP nrow, SEXP ncol, SEXP rows, SEXP naLast, SEXP decreasing);
RcppExport SEXP _bigmemory_OrderRNumericMatrixCols(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP rowsSEXP, SEXP naLastSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type naLast(naLastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(OrderRNumericMatrixCols(matrixVector, nrow, ncol, rows, naLast, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// OrderBigMatrixCols
SEXP OrderBigMatrixCols(SEXP address, SEXP rows, SEXP naLast, SEXP decreasing);
RcppExport SEXP _bigmemory_OrderBigMatrixCols(SEXP addressSEXP, SEXP rowsSEXP, SEXP naLastSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type naLast(naLastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(OrderBigMatrixCols(address, rows, naLast, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// CCleanIndices
SEXP CCleanIndices(SEXP indices, SEXP rc);
RcppExport SEXP _bigmemory_CCleanIndices(SEXP indicesSEXP, SEXP rcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rc(rcSEXP);
    rcpp_result_gen = Rcpp::wrap(CCleanIndices(indices, rc));
    return rcpp_result_gen;
END_RCPP
}
// HasRowColNames
SEXP HasRowColNames(SEXP address);
RcppExport SEXP _bigmemory_HasRowColNames(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(HasRowColNames(address));
    return rcpp_result_gen;
END_RCPP
}
// GetIndexRowNames
SEXP GetIndexRowNames(SEXP address, SEXP indices_);
RcppExport SEXP _bigmemory_GetIndexRowNames(SEXP addressSEXP, SEXP indices_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type indices_(indices_SEXP);
    rcpp_result_gen = Rcpp::wrap(GetIndexRowNames(address, indices_));
    return rcpp_result_gen;
END_RCPP
}
// GetIndexColNames
SEXP GetIndexColNames(SEXP address, SEXP indices_);
RcppExport SEXP _bigmemory_GetIndexColNames(SEXP addressSEXP, SEXP indices_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type indices_(indices_SEXP);
    rcpp_result_gen = Rcpp::wrap(GetIndexColNames(address, indices_));
    return rcpp_result_gen;
END_RCPP
}
// GetColumnNamesBM
SEXP GetColumnNamesBM(SEXP address);
RcppExport SEXP _bigmemory_GetColumnNamesBM(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(GetColumnNamesBM(address));
    return rcpp_result_gen;
END_RCPP
}
// GetRowNamesBM
SEXP GetRowNamesBM(SEXP address);
RcppExport SEXP _bigmemory_GetRowNamesBM(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(GetRowNamesBM(address));
    return rcpp_result_gen;
END_RCPP
}
// SetColumnNames
void SetColumnNames(SEXP address, SEXP columnNames);
RcppExport SEXP _bigmemory_SetColumnNames(SEXP addressSEXP, SEXP columnNamesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type columnNames(columnNamesSEXP);
    SetColumnNames(address, columnNames);
    return R_NilValue;
END_RCPP
}
// SetRowNames
void SetRowNames(SEXP address, SEXP rowNames);
RcppExport SEXP _bigmemory_SetRowNames(SEXP addressSEXP, SEXP rowNamesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rowNames(rowNamesSEXP);
    SetRowNames(address, rowNames);
    return R_NilValue;
END_RCPP
}
// IsReadOnly
SEXP IsReadOnly(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_IsReadOnly(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(IsReadOnly(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// CIsSubMatrix
SEXP CIsSubMatrix(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_CIsSubMatrix(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(CIsSubMatrix(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// CGetNrow
SEXP CGetNrow(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_CGetNrow(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(CGetNrow(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// CGetNcol
SEXP CGetNcol(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_CGetNcol(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(CGetNcol(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// CGetType
SEXP CGetType(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_CGetType(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(CGetType(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// IsSharedMemoryBigMatrix
SEXP IsSharedMemoryBigMatrix(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_IsSharedMemoryBigMatrix(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(IsSharedMemoryBigMatrix(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// IsFileBackedBigMatrix
SEXP IsFileBackedBigMatrix(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_IsFileBackedBigMatrix(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(IsFileBackedBigMatrix(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// IsSeparated
SEXP IsSeparated(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_IsSeparated(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(IsSeparated(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// SetRowOffsetInfo
void SetRowOffsetInfo(SEXP bigMatAddr, SEXP rowOffset, SEXP numRows);
RcppExport SEXP _bigmemory_SetRowOffsetInfo(SEXP bigMatAddrSEXP, SEXP rowOffsetSEXP, SEXP numRowsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rowOffset(rowOffsetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type numRows(numRowsSEXP);
    SetRowOffsetInfo(bigMatAddr, rowOffset, numRows);
    return R_NilValue;
END_RCPP
}
// SetColumnOffsetInfo
void SetColumnOffsetInfo(SEXP bigMatAddr, SEXP colOffset, SEXP numCols);
RcppExport SEXP _bigmemory_SetColumnOffsetInfo(SEXP bigMatAddrSEXP, SEXP colOffsetSEXP, SEXP numColsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colOffset(colOffsetSEXP);
    Rcpp::traits::input_parameter< SEXP >::type numCols(numColsSEXP);
    SetColumnOffsetInfo(bigMatAddr, colOffset, numCols);
    return R_NilValue;
END_RCPP
}
// GetRowOffset
SEXP GetRowOffset(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_GetRowOffset(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetRowOffset(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// GetColOffset
Rcpp::NumericVector GetColOffset(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_GetColOffset(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetColOffset(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// GetTotalColumns
SEXP GetTotalColumns(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_GetTotalColumns(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetTotalColumns(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// GetTotalRows
SEXP GetTotalRows(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_GetTotalRows(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetTotalRows(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// GetTypeString
Rcpp::String GetTypeString(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_GetTypeString(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetTypeString(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// GetMatrixSize
SEXP GetMatrixSize(SEXP bigMat);
RcppExport SEXP _bigmemory_GetMatrixSize(SEXP bigMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMat(bigMatSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMatrixSize(bigMat));
    return rcpp_result_gen;
END_RCPP
}
// MWhichBigMatrix
SEXP MWhichBigMatrix(SEXP bigMatAddr, SEXP selectColumn, SEXP minVal, SEXP maxVal, SEXP chkMin, SEXP chkMax, SEXP opVal);
RcppExport SEXP _bigmemory_MWhichBigMatrix(SEXP bigMatAddrSEXP, SEXP selectColumnSEXP, SEXP minValSEXP, SEXP maxValSEXP, SEXP chkMinSEXP, SEXP chkMaxSEXP, SEXP opValSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type selectColumn(selectColumnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type minVal(minValSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxVal(maxValSEXP);
    Rcpp::traits::input_parameter< SEXP >::type chkMin(chkMinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type chkMax(chkMaxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type opVal(opValSEXP);
    rcpp_result_gen = Rcpp::wrap(MWhichBigMatrix(bigMatAddr, selectColumn, minVal, maxVal, chkMin, chkMax, opVal));
    return rcpp_result_gen;
END_RCPP
}
// MWhichRIntMatrix
SEXP MWhichRIntMatrix(SEXP matrixVector, SEXP nrow, SEXP selectColumn, SEXP minVal, SEXP maxVal, SEXP chkMin, SEXP chkMax, SEXP opVal);
RcppExport SEXP _bigmemory_MWhichRIntMatrix(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP selectColumnSEXP, SEXP minValSEXP, SEXP maxValSEXP, SEXP chkMinSEXP, SEXP chkMaxSEXP, SEXP opValSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type selectColumn(selectColumnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type minVal(minValSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxVal(maxValSEXP);
    Rcpp::traits::input_parameter< SEXP >::type chkMin(chkMinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type chkMax(chkMaxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type opVal(opValSEXP);
    rcpp_result_gen = Rcpp::wrap(MWhichRIntMatrix(matrixVector, nrow, selectColumn, minVal, maxVal, chkMin, chkMax, opVal));
    return rcpp_result_gen;
END_RCPP
}
// MWhichRNumericMatrix
SEXP MWhichRNumericMatrix(SEXP matrixVector, SEXP nrow, SEXP selectColumn, SEXP minVal, SEXP maxVal, SEXP chkMin, SEXP chkMax, SEXP opVal);
RcppExport SEXP _bigmemory_MWhichRNumericMatrix(SEXP matrixVectorSEXP, SEXP nrowSEXP, SEXP selectColumnSEXP, SEXP minValSEXP, SEXP maxValSEXP, SEXP chkMinSEXP, SEXP chkMaxSEXP, SEXP opValSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type matrixVector(matrixVectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type selectColumn(selectColumnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type minVal(minValSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxVal(maxValSEXP);
    Rcpp::traits::input_parameter< SEXP >::type chkMin(chkMinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type chkMax(chkMaxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type opVal(opValSEXP);
    rcpp_result_gen = Rcpp::wrap(MWhichRNumericMatrix(matrixVector, nrow, selectColumn, minVal, maxVal, chkMin, chkMax, opVal));
    return rcpp_result_gen;
END_RCPP
}
// CCountLines
SEXP CCountLines(SEXP fileName);
RcppExport SEXP _bigmemory_CCountLines(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CCountLines(fileName));
    return rcpp_result_gen;
END_RCPP
}
// ReadMatrix
SEXP ReadMatrix(SEXP fileName, SEXP bigMatAddr, SEXP firstLine, SEXP numLines, SEXP numCols, SEXP separator, SEXP hasRowNames, SEXP useRowNames);
RcppExport SEXP _bigmemory_ReadMatrix(SEXP fileNameSEXP, SEXP bigMatAddrSEXP, SEXP firstLineSEXP, SEXP numLinesSEXP, SEXP numColsSEXP, SEXP separatorSEXP, SEXP hasRowNamesSEXP, SEXP useRowNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type firstLine(firstLineSEXP);
    Rcpp::traits::input_parameter< SEXP >::type numLines(numLinesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type numCols(numColsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type separator(separatorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type hasRowNames(hasRowNamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type useRowNames(useRowNamesSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadMatrix(fileName, bigMatAddr, firstLine, numLines, numCols, separator, hasRowNames, useRowNames));
    return rcpp_result_gen;
END_RCPP
}
// WriteMatrix
void WriteMatrix(SEXP bigMatAddr, SEXP fileName, SEXP rowNames, SEXP colNames, SEXP sep);
RcppExport SEXP _bigmemory_WriteMatrix(SEXP bigMatAddrSEXP, SEXP fileNameSEXP, SEXP rowNamesSEXP, SEXP colNamesSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rowNames(rowNamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colNames(colNamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sep(sepSEXP);
    WriteMatrix(bigMatAddr, fileName, rowNames, colNames, sep);
    return R_NilValue;
END_RCPP
}
// GetMatrixElements
SEXP GetMatrixElements(SEXP bigMatAddr, SEXP col, SEXP row);
RcppExport SEXP _bigmemory_GetMatrixElements(SEXP bigMatAddrSEXP, SEXP colSEXP, SEXP rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMatrixElements(bigMatAddr, col, row));
    return rcpp_result_gen;
END_RCPP
}
// GetMatrixRows
SEXP GetMatrixRows(SEXP bigMatAddr, SEXP row);
RcppExport SEXP _bigmemory_GetMatrixRows(SEXP bigMatAddrSEXP, SEXP rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMatrixRows(bigMatAddr, row));
    return rcpp_result_gen;
END_RCPP
}
// GetMatrixCols
SEXP GetMatrixCols(SEXP bigMatAddr, SEXP col);
RcppExport SEXP _bigmemory_GetMatrixCols(SEXP bigMatAddrSEXP, SEXP colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMatrixCols(bigMatAddr, col));
    return rcpp_result_gen;
END_RCPP
}
// GetMatrixAll
SEXP GetMatrixAll(SEXP bigMatAddr);
RcppExport SEXP _bigmemory_GetMatrixAll(SEXP bigMatAddrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMatrixAll(bigMatAddr));
    return rcpp_result_gen;
END_RCPP
}
// SetMatrixElements
void SetMatrixElements(SEXP bigMatAddr, SEXP col, SEXP row, SEXP values);
RcppExport SEXP _bigmemory_SetMatrixElements(SEXP bigMatAddrSEXP, SEXP colSEXP, SEXP rowSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    SetMatrixElements(bigMatAddr, col, row, values);
    return R_NilValue;
END_RCPP
}
// SetIndivVectorMatrixElements
void SetIndivVectorMatrixElements(SEXP bigMatAddr, NumericVector elems, NumericVector inVec);
RcppExport SEXP _bigmemory_SetIndivVectorMatrixElements(SEXP bigMatAddrSEXP, SEXP elemsSEXP, SEXP inVecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type elems(elemsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inVec(inVecSEXP);
    SetIndivVectorMatrixElements(bigMatAddr, elems, inVec);
    return R_NilValue;
END_RCPP
}
// SetIndivMatrixElements
void SetIndivMatrixElements(SEXP bigMatAddr, SEXP col, SEXP row, SEXP values);
RcppExport SEXP _bigmemory_SetIndivMatrixElements(SEXP bigMatAddrSEXP, SEXP colSEXP, SEXP rowSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    SetIndivMatrixElements(bigMatAddr, col, row, values);
    return R_NilValue;
END_RCPP
}
// SetMatrixAll
void SetMatrixAll(SEXP bigMatAddr, SEXP values);
RcppExport SEXP _bigmemory_SetMatrixAll(SEXP bigMatAddrSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    SetMatrixAll(bigMatAddr, values);
    return R_NilValue;
END_RCPP
}
// SetMatrixCols
void SetMatrixCols(SEXP bigMatAddr, SEXP col, SEXP values);
RcppExport SEXP _bigmemory_SetMatrixCols(SEXP bigMatAddrSEXP, SEXP colSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    SetMatrixCols(bigMatAddr, col, values);
    return R_NilValue;
END_RCPP
}
// SetMatrixRows
void SetMatrixRows(SEXP bigMatAddr, SEXP row, SEXP values);
RcppExport SEXP _bigmemory_SetMatrixRows(SEXP bigMatAddrSEXP, SEXP rowSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type bigMatAddr(bigMatAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    SetMatrixRows(bigMatAddr, row, values);
    return R_NilValue;
END_RCPP
}
// CreateSharedMatrix
SEXP CreateSharedMatrix(SEXP row, SEXP col, SEXP colnames, SEXP rownames, SEXP typeLength, SEXP ini, SEXP separated);
RcppExport SEXP _bigmemory_CreateSharedMatrix(SEXP rowSEXP, SEXP colSEXP, SEXP colnamesSEXP, SEXP rownamesSEXP, SEXP typeLengthSEXP, SEXP iniSEXP, SEXP separatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colnames(colnamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rownames(rownamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type typeLength(typeLengthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ini(iniSEXP);
    Rcpp::traits::input_parameter< SEXP >::type separated(separatedSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateSharedMatrix(row, col, colnames, rownames, typeLength, ini, separated));
    return rcpp_result_gen;
END_RCPP
}
// CreateLocalMatrix
SEXP CreateLocalMatrix(SEXP row, SEXP col, SEXP colnames, SEXP rownames, SEXP typeLength, SEXP ini, SEXP separated);
RcppExport SEXP _bigmemory_CreateLocalMatrix(SEXP rowSEXP, SEXP colSEXP, SEXP colnamesSEXP, SEXP rownamesSEXP, SEXP typeLengthSEXP, SEXP iniSEXP, SEXP separatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colnames(colnamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rownames(rownamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type typeLength(typeLengthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ini(iniSEXP);
    Rcpp::traits::input_parameter< SEXP >::type separated(separatedSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateLocalMatrix(row, col, colnames, rownames, typeLength, ini, separated));
    return rcpp_result_gen;
END_RCPP
}
// CreateFileBackedBigMatrix
SEXP CreateFileBackedBigMatrix(SEXP fileName, SEXP filePath, SEXP row, SEXP col, SEXP colnames, SEXP rownames, SEXP typeLength, SEXP ini, SEXP separated);
RcppExport SEXP _bigmemory_CreateFileBackedBigMatrix(SEXP fileNameSEXP, SEXP filePathSEXP, SEXP rowSEXP, SEXP colSEXP, SEXP colnamesSEXP, SEXP rownamesSEXP, SEXP typeLengthSEXP, SEXP iniSEXP, SEXP separatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type filePath(filePathSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row(rowSEXP);
    Rcpp::traits::input_parameter< SEXP >::type col(colSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colnames(colnamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rownames(rownamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type typeLength(typeLengthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ini(iniSEXP);
    Rcpp::traits::input_parameter< SEXP >::type separated(separatedSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateFileBackedBigMatrix(fileName, filePath, row, col, colnames, rownames, typeLength, ini, separated));
    return rcpp_result_gen;
END_RCPP
}
// CAttachSharedBigMatrix
SEXP CAttachSharedBigMatrix(SEXP sharedName, SEXP rows, SEXP cols, SEXP rowNames, SEXP colNames, SEXP typeLength, SEXP separated, SEXP readOnly);
RcppExport SEXP _bigmemory_CAttachSharedBigMatrix(SEXP sharedNameSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP rowNamesSEXP, SEXP colNamesSEXP, SEXP typeLengthSEXP, SEXP separatedSEXP, SEXP readOnlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sharedName(sharedNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rowNames(rowNamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colNames(colNamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type typeLength(typeLengthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type separated(separatedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type readOnly(readOnlySEXP);
    rcpp_result_gen = Rcpp::wrap(CAttachSharedBigMatrix(sharedName, rows, cols, rowNames, colNames, typeLength, separated, readOnly));
    return rcpp_result_gen;
END_RCPP
}
// CAttachFileBackedBigMatrix
SEXP CAttachFileBackedBigMatrix(SEXP fileName, SEXP filePath, SEXP rows, SEXP cols, SEXP rowNames, SEXP colNames, SEXP typeLength, SEXP separated, SEXP readOnly);
RcppExport SEXP _bigmemory_CAttachFileBackedBigMatrix(SEXP fileNameSEXP, SEXP filePathSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP rowNamesSEXP, SEXP colNamesSEXP, SEXP typeLengthSEXP, SEXP separatedSEXP, SEXP readOnlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type filePath(filePathSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rowNames(rowNamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colNames(colNamesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type typeLength(typeLengthSEXP);
    Rcpp::traits::input_parameter< SEXP >::type separated(separatedSEXP);
    Rcpp::traits::input_parameter< SEXP >::type readOnly(readOnlySEXP);
    rcpp_result_gen = Rcpp::wrap(CAttachFileBackedBigMatrix(fileName, filePath, rows, cols, rowNames, colNames, typeLength, separated, readOnly));
    return rcpp_result_gen;
END_RCPP
}
// SharedName
SEXP SharedName(SEXP address);
RcppExport SEXP _bigmemory_SharedName(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(SharedName(address));
    return rcpp_result_gen;
END_RCPP
}
// FileName
SEXP FileName(SEXP address);
RcppExport SEXP _bigmemory_FileName(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(FileName(address));
    return rcpp_result_gen;
END_RCPP
}
// DirName
SEXP DirName(SEXP address);
RcppExport SEXP _bigmemory_DirName(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(DirName(address));
    return rcpp_result_gen;
END_RCPP
}
// Flush
SEXP Flush(SEXP address);
RcppExport SEXP _bigmemory_Flush(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(Flush(address));
    return rcpp_result_gen;
END_RCPP
}
// IsShared
SEXP IsShared(SEXP address);
RcppExport SEXP _bigmemory_IsShared(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(IsShared(address));
    return rcpp_result_gen;
END_RCPP
}
// isnil
SEXP isnil(SEXP address);
RcppExport SEXP _bigmemory_isnil(SEXP addressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type address(addressSEXP);
    rcpp_result_gen = Rcpp::wrap(isnil(address));
    return rcpp_result_gen;
END_RCPP
}
// CDeepCopy
SEXP CDeepCopy(SEXP inAddr, SEXP outAddr, SEXP rowInds, SEXP colInds, SEXP typecast_warning);
RcppExport SEXP _bigmemory_CDeepCopy(SEXP inAddrSEXP, SEXP outAddrSEXP, SEXP rowIndsSEXP, SEXP colIndsSEXP, SEXP typecast_warningSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type inAddr(inAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type outAddr(outAddrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rowInds(rowIndsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type colInds(colIndsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type typecast_warning(typecast_warningSEXP);
    rcpp_result_gen = Rcpp::wrap(CDeepCopy(inAddr, outAddr, rowInds, colInds, typecast_warning));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bigmemory_GetIndivMatrixElements", (DL_FUNC) &_bigmemory_GetIndivMatrixElements, 3},
    {"_bigmemory_GetIndivVectorMatrixElements", (DL_FUNC) &_bigmemory_GetIndivVectorMatrixElements, 2},
    {"_bigmemory_ReorderRIntMatrix", (DL_FUNC) &_bigmemory_ReorderRIntMatrix, 4},
    {"_bigmemory_ReorderRNumericMatrix", (DL_FUNC) &_bigmemory_ReorderRNumericMatrix, 4},
    {"_bigmemory_ReorderBigMatrix", (DL_FUNC) &_bigmemory_ReorderBigMatrix, 2},
    {"_bigmemory_ReorderRIntMatrixCols", (DL_FUNC) &_bigmemory_ReorderRIntMatrixCols, 4},
    {"_bigmemory_ReorderRNumericMatrixCols", (DL_FUNC) &_bigmemory_ReorderRNumericMatrixCols, 4},
    {"_bigmemory_ReorderRRawMatrixCols", (DL_FUNC) &_bigmemory_ReorderRRawMatrixCols, 4},
    {"_bigmemory_ReorderBigMatrixCols", (DL_FUNC) &_bigmemory_ReorderBigMatrixCols, 2},
    {"_bigmemory_OrderRIntMatrix", (DL_FUNC) &_bigmemory_OrderRIntMatrix, 5},
    {"_bigmemory_OrderRNumericMatrix", (DL_FUNC) &_bigmemory_OrderRNumericMatrix, 5},
    {"_bigmemory_OrderBigMatrix", (DL_FUNC) &_bigmemory_OrderBigMatrix, 4},
    {"_bigmemory_OrderRIntMatrixCols", (DL_FUNC) &_bigmemory_OrderRIntMatrixCols, 6},
    {"_bigmemory_OrderRNumericMatrixCols", (DL_FUNC) &_bigmemory_OrderRNumericMatrixCols, 6},
    {"_bigmemory_OrderBigMatrixCols", (DL_FUNC) &_bigmemory_OrderBigMatrixCols, 4},
    {"_bigmemory_CCleanIndices", (DL_FUNC) &_bigmemory_CCleanIndices, 2},
    {"_bigmemory_HasRowColNames", (DL_FUNC) &_bigmemory_HasRowColNames, 1},
    {"_bigmemory_GetIndexRowNames", (DL_FUNC) &_bigmemory_GetIndexRowNames, 2},
    {"_bigmemory_GetIndexColNames", (DL_FUNC) &_bigmemory_GetIndexColNames, 2},
    {"_bigmemory_GetColumnNamesBM", (DL_FUNC) &_bigmemory_GetColumnNamesBM, 1},
    {"_bigmemory_GetRowNamesBM", (DL_FUNC) &_bigmemory_GetRowNamesBM, 1},
    {"_bigmemory_SetColumnNames", (DL_FUNC) &_bigmemory_SetColumnNames, 2},
    {"_bigmemory_SetRowNames", (DL_FUNC) &_bigmemory_SetRowNames, 2},
    {"_bigmemory_IsReadOnly", (DL_FUNC) &_bigmemory_IsReadOnly, 1},
    {"_bigmemory_CIsSubMatrix", (DL_FUNC) &_bigmemory_CIsSubMatrix, 1},
    {"_bigmemory_CGetNrow", (DL_FUNC) &_bigmemory_CGetNrow, 1},
    {"_bigmemory_CGetNcol", (DL_FUNC) &_bigmemory_CGetNcol, 1},
    {"_bigmemory_CGetType", (DL_FUNC) &_bigmemory_CGetType, 1},
    {"_bigmemory_IsSharedMemoryBigMatrix", (DL_FUNC) &_bigmemory_IsSharedMemoryBigMatrix, 1},
    {"_bigmemory_IsFileBackedBigMatrix", (DL_FUNC) &_bigmemory_IsFileBackedBigMatrix, 1},
    {"_bigmemory_IsSeparated", (DL_FUNC) &_bigmemory_IsSeparated, 1},
    {"_bigmemory_SetRowOffsetInfo", (DL_FUNC) &_bigmemory_SetRowOffsetInfo, 3},
    {"_bigmemory_SetColumnOffsetInfo", (DL_FUNC) &_bigmemory_SetColumnOffsetInfo, 3},
    {"_bigmemory_GetRowOffset", (DL_FUNC) &_bigmemory_GetRowOffset, 1},
    {"_bigmemory_GetColOffset", (DL_FUNC) &_bigmemory_GetColOffset, 1},
    {"_bigmemory_GetTotalColumns", (DL_FUNC) &_bigmemory_GetTotalColumns, 1},
    {"_bigmemory_GetTotalRows", (DL_FUNC) &_bigmemory_GetTotalRows, 1},
    {"_bigmemory_GetTypeString", (DL_FUNC) &_bigmemory_GetTypeString, 1},
    {"_bigmemory_GetMatrixSize", (DL_FUNC) &_bigmemory_GetMatrixSize, 1},
    {"_bigmemory_MWhichBigMatrix", (DL_FUNC) &_bigmemory_MWhichBigMatrix, 7},
    {"_bigmemory_MWhichRIntMatrix", (DL_FUNC) &_bigmemory_MWhichRIntMatrix, 8},
    {"_bigmemory_MWhichRNumericMatrix", (DL_FUNC) &_bigmemory_MWhichRNumericMatrix, 8},
    {"_bigmemory_CCountLines", (DL_FUNC) &_bigmemory_CCountLines, 1},
    {"_bigmemory_ReadMatrix", (DL_FUNC) &_bigmemory_ReadMatrix, 8},
    {"_bigmemory_WriteMatrix", (DL_FUNC) &_bigmemory_WriteMatrix, 5},
    {"_bigmemory_GetMatrixElements", (DL_FUNC) &_bigmemory_GetMatrixElements, 3},
    {"_bigmemory_GetMatrixRows", (DL_FUNC) &_bigmemory_GetMatrixRows, 2},
    {"_bigmemory_GetMatrixCols", (DL_FUNC) &_bigmemory_GetMatrixCols, 2},
    {"_bigmemory_GetMatrixAll", (DL_FUNC) &_bigmemory_GetMatrixAll, 1},
    {"_bigmemory_SetMatrixElements", (DL_FUNC) &_bigmemory_SetMatrixElements, 4},
    {"_bigmemory_SetIndivVectorMatrixElements", (DL_FUNC) &_bigmemory_SetIndivVectorMatrixElements, 3},
    {"_bigmemory_SetIndivMatrixElements", (DL_FUNC) &_bigmemory_SetIndivMatrixElements, 4},
    {"_bigmemory_SetMatrixAll", (DL_FUNC) &_bigmemory_SetMatrixAll, 2},
    {"_bigmemory_SetMatrixCols", (DL_FUNC) &_bigmemory_SetMatrixCols, 3},
    {"_bigmemory_SetMatrixRows", (DL_FUNC) &_bigmemory_SetMatrixRows, 3},
    {"_bigmemory_CreateSharedMatrix", (DL_FUNC) &_bigmemory_CreateSharedMatrix, 7},
    {"_bigmemory_CreateLocalMatrix", (DL_FUNC) &_bigmemory_CreateLocalMatrix, 7},
    {"_bigmemory_CreateFileBackedBigMatrix", (DL_FUNC) &_bigmemory_CreateFileBackedBigMatrix, 9},
    {"_bigmemory_CAttachSharedBigMatrix", (DL_FUNC) &_bigmemory_CAttachSharedBigMatrix, 8},
    {"_bigmemory_CAttachFileBackedBigMatrix", (DL_FUNC) &_bigmemory_CAttachFileBackedBigMatrix, 9},
    {"_bigmemory_SharedName", (DL_FUNC) &_bigmemory_SharedName, 1},
    {"_bigmemory_FileName", (DL_FUNC) &_bigmemory_FileName, 1},
    {"_bigmemory_DirName", (DL_FUNC) &_bigmemory_DirName, 1},
    {"_bigmemory_Flush", (DL_FUNC) &_bigmemory_Flush, 1},
    {"_bigmemory_IsShared", (DL_FUNC) &_bigmemory_IsShared, 1},
    {"_bigmemory_isnil", (DL_FUNC) &_bigmemory_isnil, 1},
    {"_bigmemory_CDeepCopy", (DL_FUNC) &_bigmemory_CDeepCopy, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_bigmemory(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
